image: Visual Studio 2019
clone_depth: 5

environment:

  CONDA_PATH: "C:\\Miniconda"

  matrix:
    - PYTHON_VERSION: "3.6"
    - PYTHON_VERSION: "3.7"
    - PYTHON_VERSION: "3.8"

platform:
    - x64

install:
    # Use the pre-installed Miniconda for the desired arch
    - ps: if($env:PYTHON_VERSION -eq '3.6')
            { $env:CONDA_PATH="$($env:CONDA_PATH)36" }
    - ps: if($env:PYTHON_VERSION -eq '3.7')
            { $env:CONDA_PATH="$($env:CONDA_PATH)37" }
    - ps: if($env:PLATFORM -eq 'x64')
            { $env:CONDA_PATH="$($env:CONDA_PATH)-x64" }
    - ps: $env:path="$($env:CONDA_PATH);$($env:CONDA_PATH)\Scripts;$($env:CONDA_PATH)\Library\bin;$($env:PATH)"
    - cmd: conda config --set always_yes yes --set changeps1 no
    - cmd: conda update -q conda
    # Useful for debugging any issues with conda
    - cmd: conda info -a
    - cmd: sed -i -e s/python=3/python=%PYTHON_VERSION%/ environment.yml
    - cmd: conda env create -q -f environment.yml
    - cmd: activate devel
    - cmd: pip install sphinx_rtd_theme==0.2.5b1.post1 -f https://unidata-python.s3.amazonaws.com/wheelhouse/index.html
    - cmd: python --version
    - cmd: conda list
    - cmd: pip install ".[test]"
    - cmd: flake8 --version

# Skip .NET project specific build phase.
build: off

test_script:
    - cmd: set TEST_DATA_DIR=%APPVEYOR_BUILD_FOLDER%\\staticdata
    - cmd: pytest -s --junitxml=tests.xml --flake8 --mpl --cov=metpy -W error::metpy.deprecation.MetpyDeprecationWarning
    - cmd: cd docs
    - cmd: make overridecheck html
    - cmd: cd ..

on_finish:
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
    - cmd: pip install codecov
    - cmd: codecov -e PYTHON_VERSION PLATFORM

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/0ea592876f591013ca9f
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
