# Create full conda environment for development, including some useful tools
name: devel
channels:
  - conda-forge/label/testing
  - conda-forge
dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - pint
  - netcdf4
  - xarray
  - pandas
  - jupyter
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - pytest>=2.4
  - pytest-cov
  - pytest-flake8
  - pytest-mpl
  - flake8-builtins!=1.4.0
  - flake8-comprehensions=1.4.1
  - flake8-copyright
  - flake8-docstrings
  - flake8-import-order
  - flake8-mutable
  - flake8-pep3101
  - flake8-print
  - flake8-quotes
  - flake8-rst-docstrings
  - pep8-naming
  - pyproj
  - cartopy
  - doc8
  - m2r
  - pooch>=0.1
  - setuptools_scm
