# Create full conda environment for development, including some useful tools
name: devel
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - pint
  - netcdf4
  - jupyter
  - sphinx
  - pytest
  - pytest-cov
  - pytest-mpl
  - pytest-runner
  - flake8
  - pep8-naming
  - pyproj
  - cartopy
